# Generated by Django 2.1.2 on 2018-11-24 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('block_id', models.IntegerField()),
                ('block_address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=50, null=True)),
                ('issueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Grantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('issue_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('a', 'APPROVED'), ('p', 'PENDING'), ('r', 'REJECTED')], default='PENDING', max_length=1)),
                ('amount', models.IntegerField()),
                ('repaid', models.IntegerField(null=True)),
                ('interest', models.IntegerField()),
                ('issue_date', models.DateField(max_length=20)),
                ('due_date', models.DateField(max_length=20)),
                ('coop_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_address', models.CharField(max_length=255)),
                ('block_id', models.IntegerField()),
                ('block_address', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Bank')),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cooperative')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='investment_grantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Grantee'),
        ),
        migrations.AddField(
            model_name='bank',
            name='coop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cooperative'),
        ),
        migrations.AddField(
            model_name='bank',
            name='ledger',
            field=models.ManyToManyField(to='app.Ledger'),
        ),
    ]
