# Generated by Django 2.1.2 on 2018-11-24 06:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_cooperatives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cooperatives',
            new_name='Cooperative',
        ),
    ]
