# Generated by Django 2.1.2 on 2018-11-24 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20181124_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='user',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
