# Generated by Django 2.1.2 on 2018-11-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cooperative'),
        ),
    ]
