# Generated by Django 2.1.2 on 2018-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181124_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
